services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
      POSTGRES_DB: ${DB_NAME}  
    ports:
      - '${DB_PORT}:${DB_PORT}' 

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - '${ADMINER_PORT}:${ADMINER_PORT}'  
    environment:
      ADMINER_DESIGN: "hydra"
