version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: mysql_inventory
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: inventario
      MYSQL_USER: username
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: adminer_inventory
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DESIGN: "hydra"

volumes:
  db_data:
    driver: local
